---
title: "FinalReport"
format: html
editor: visual
author: Meghan Myles and Owen Fiore
---

# Student Exam Excellence

## Abstract

Standardized tests have been used to try and evaluate how much each student has learned in a classroom.  However, it is possible that predetermined factors related to a student's socioeconomic status play a significant role in how student's learn and how well they perform on standardized tests.  It is important to understand that although standardized tests are meant to level the playing field between students, there are many elements that can contribute to student performance on standardized tests.

## Introduction

It is important to be able to measure students’ academic performance, as such measurements can help guide decisions about best educational practices at every level. They can help to identify individual students who are performing poorly in order to give them more individualized instruction. They can identify districts which are underperforming in order to better invest educational resources. They can identify subject areas in which students are consistently underperforming in order to tailor teaching methods. One method of evaluating students’ academic performance is by investigating their scores on standardized exams.

It is desirable to explore factors influencing standardized test scores to determine if standardized tests are performing as they should be. Ideally we would like to see that standardized test scores are poorly correlated with socioeconomic factors and very strongly correlated with how much students study for them. This would be indicative that standardized test scores and thus learning are not impacted very much by prior factors and that students of all backgrounds have the chance to succeed.

There have been a number of investigations into the interactions between socioeconomic factors and student academic performance. According to the NIH, around half of people who grew up in a high-income family have a bachelor’s degree by the age of 25, while only about 10% of people from low-income families have a bachelor’s degree by 25. In addition, there tend to be fewer AP classes offered in schools which traditionally serve low-income and minority students (National Institutes of Health). In addition, on certain standardized tests, some groups tend to consistently outperform others. On the SAT II writing exam, the average white student outperformed the average student of color (Thomas 2004). A University of South Florida study showed that students’ SAT and ACT scores were not predictive of their college academic performance (Micceri 2010). In a 2009 study, Black and latino students performed lower on the MCAT, on average, than white students (Davis 2013). It is clear that standardized test scores are not necessarily only indicative of academic success - it seems that they also capture variation introduced by socioeconomic factors.

We will examine a dataset detailing students’ standardized test scores, as well as measures for several socioeconomic factors and student dedication to academics. In doing so, we will be able to determine whether or not this standardized test is appropriate for measuring true student achievement.


## Data Description:

Here is a link to the kaggla data: <https://www.kaggle.com/datasets/desalegngeb/students-exam-scores>

-   Gender: Gender of the student (male or female)
-   EthnicGroup: Ethnic group of the student (nominal groups from A to E)
-   ParentEduc: Parent education background: (ordinal groups from some high school to master's)
-   LunchType: Cost of school lunch (free/reduced or standard)
-   TestPrep: Whether the student completed a test preparation course (none or completed)
-   ParentMaritalStatus: Student's parent's marital status(nominal groups: married, single, widowed, divorced)
-   PracticeSport: How often a student plays a sport (ordinal groups from never, sometimes, regularly)
-   IsFirstChild: If the student is the eldest child in their family (yes or no)
-   NrSibling: number of siblings the student has
-   TransportMeans: how the student gets to school (schoolbus or private)
-   WklyStudyHours: how much the student self-studies (ordinal groups from 0-5, 5-10, and 10+ hours)

MathScore, ReadingScore, WritingScore are the student's math, reading, and writing scores respectively and serve as the response variable in this dataset. Scores range from 0 to 100 with 0 indicating low performance and 100 indicating perfect.

We will treat the variables Gender, EthnicGroup, ParentEduc, ParentMaritalStatus, PracticeSport, NrSibling, and TransportMeans as indicators of students’ socioeconomic status. We will treat the variables TestPrep and WklyStudyHours as indicators of students’ academic dedication.

As this dataset is fictional, it is impossible to perform any additional research on the background of the town this data came from or provide more context.

## Goal

Our goal is to determine whether or not standardized tests are performing well in measuring academic performance. Our research questions are as follows:

Do math, reading, and writing scores on this standardized test correlate with each other?
Do performances on the tests correlate with socioeconomic factors, such as highest parental education level or receiving a free/reduced lunch?
Do performances on the tests correlate with indicators of academic commitment, such as studying for many hours weekly and completing test preparation courses?
Do test scores vary significantly across gender and ethnic groups?
In all, does it appear that each of these tests are measuring true academic performance, or are they heavily influenced by other factors?

By regressing test scores on the other variables available in this dataset, we hope to be able to determine answers to these questions. We will determine whether standardized test performance is more highly correlated with socioeconomic factors or academic dedication. This will help us to determine whether or not the tests are appropriate measures of academic performance.

## Methods
In this paper we will test out the use of several different models of varying complexities
to try and best fit our data, starting with a linear model.  Regression diagnostics showed that the model was over-predicting the achievement of students who should be doing really well.  Thus we decided to implement a Generalized Linear Model to try and remedy this. A generalized linear model has a random component, systematic component, and a link function.

The random component is a probability density function from an exponential family:
\[f(y; \theta, \phi) = \exp{\frac{y\theta - b(\theta)}{a(\phi) + c(y, \phi)}} \]
where $\theta$ and $\phi > 0$ are scalar parameters, and $a$, $b$, $c$, are known functions.  The form of a Gaussian distribution with an identity link is:
\[ f(y | \mu, \sigma^2) = \frac{1}{\sqrt(2 \pi \sigma^2)} \exp(-\frac{(y - \mu)^2}{2 \sigma^2}) \]. Where $\mu$ is the mean of the distribution and $\sigma^2$ is the variance

The systematic component is the main part of the model and is a generalized form of a linear model such that for the systematic component: $\eta_i$ we have:
\[ \eta_i = \beta_0 + \sum_{j=1}^p \beta_j X_{ij} \]
To obtain this part, we implemented stepwise selection through the `step` R function in both directions, allowing both forward and backwards selection.  Forward or backwards selection is a variable selection algorithm that looks for the most significant predictors and returns a model when there cannot be any additional significant variables added.  The algorithm returned that the following parameters should be included in the model: `Male`, `ParentEduc`, `LunchDiscount`, `TestPrep`, `PracticeSport`, `IsFirstChild`, `WklyStudyHours`, and all variables of the form `EthnicGroup`. 

Male           -11.4038     0.5946 -19.178  < 2e-16 ***
ParentEduc       6.6478     0.1993  33.351  < 2e-16 ***
LunchDiscount  -29.4815     0.6233 -47.301  < 2e-16 ***
TestPrep        20.3223     0.6246  32.536  < 2e-16 ***
PracticeSport    3.5873     0.4462   8.040 9.66e-16 ***
IsFirstChild     0.8918     0.6207   1.437    0.151    
WklyStudyHours   0.5765     0.3883   1.484    0.138    
EthnicGroupA   -26.3258     1.3420 -19.616  < 2e-16 ***
EthnicGroupB   -25.8893     1.0286 -25.169  < 2e-16 ***
EthnicGroupC   -22.6609     0.9488 -23.883  < 2e-16 ***
EthnicGroupD   -13.0288     0.9828 -13.257  < 2e-16 ***

\[ g(\mu_i) = \eta_i = \beta_0 + \beta_1X__{i1} + ... + \beta_pX__{ip} \]
We choose to implement a gaussian 

## Results

## Summary and Conclusion


## References

Davis, Dwight MD; Dorsey, J. Kevin MD, PhD; Franks, Ronald D. MD; Sackett, Paul R. PhD; Searcy, Cynthia A. PhD; Zhao, Xiaohui PhD. Do Racial and Ethnic Group Differences in Performance on the MCAT Exam Reflect Test Bias?. Academic Medicine 88(5):p 593-602, May 2013. | DOI: 10.1097/ACM.0b013e318286803a

“Individuals from Disadvantaged Backgrounds.” National Institutes of Health, U.S. Department of Health and Human Services, extramural-diversity.nih.gov/diversity-matters/disadvantaged-backgrounds. 

Micceri, Theodore. “Assessing the Usefulness of SAT and Act Tests in Minority Admissions.” Online Submission, Institute of Educational Sciences, 31 Dec. 2009, eric.ed.gov/?id=ED510111. 

Thomas, M.K. (2004), The SAT II: Minority/Majority Test-Score Gaps and What They Could Mean for College Admissions. Social Science Quarterly, 85: 1318-1334. https://doi.org/10.1111/j.0038-4941.2004.00278.x
